# coding: utf-8

"""
    WASM OJ Wonderland API

    You can interact with WASM OJ Wonderland through this API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: jacob@csie.cool
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import woj
from woj.models.api_auth_send_post400_response import ApiAuthSendPost400Response  # noqa: E501
from woj.rest import ApiException

class TestApiAuthSendPost400Response(unittest.TestCase):
    """ApiAuthSendPost400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiAuthSendPost400Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiAuthSendPost400Response`
        """
        model = woj.models.api_auth_send_post400_response.ApiAuthSendPost400Response()  # noqa: E501
        if include_optional :
            return ApiAuthSendPost400Response(
                message = ''
            )
        else :
            return ApiAuthSendPost400Response(
                message = '',
        )
        """

    def testApiAuthSendPost400Response(self):
        """Test ApiAuthSendPost400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
