# coding: utf-8

"""
    WASM OJ Wonderland API

    You can interact with WASM OJ Wonderland through this API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: jacob@csie.cool
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import woj
from woj.api.problem_api import ProblemApi  # noqa: E501
from woj.rest import ApiException


class TestProblemApi(unittest.TestCase):
    """ProblemApi unit test stubs"""

    def setUp(self):
        self.api = woj.api.problem_api.ProblemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_problem_get(self):
        """Test case for api_problem_get

        """
        pass

    def test_api_problem_id_get(self):
        """Test case for api_problem_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
