# coding: utf-8

"""
    WASM OJ Wonderland API

    You can interact with WASM OJ Wonderland through this API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: jacob@csie.cool
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import woj
from woj.models.api_problem_get200_response import ApiProblemGet200Response  # noqa: E501
from woj.rest import ApiException

class TestApiProblemGet200Response(unittest.TestCase):
    """ApiProblemGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiProblemGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiProblemGet200Response`
        """
        model = woj.models.api_problem_get200_response.ApiProblemGet200Response()  # noqa: E501
        if include_optional :
            return ApiProblemGet200Response(
                problems = [
                    woj.models._api_problem_get_200_response_problems_inner._api_problem_get_200_response_problems_inner(
                        sub = {
                            'key' : 1.337
                            }, 
                        id = '', 
                        name = '', 
                        tags = [
                            ''
                            ], )
                    ]
            )
        else :
            return ApiProblemGet200Response(
                problems = [
                    woj.models._api_problem_get_200_response_problems_inner._api_problem_get_200_response_problems_inner(
                        sub = {
                            'key' : 1.337
                            }, 
                        id = '', 
                        name = '', 
                        tags = [
                            ''
                            ], )
                    ],
        )
        """

    def testApiProblemGet200Response(self):
        """Test ApiProblemGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
