# coding: utf-8

"""
    WASM OJ Wonderland API

    You can interact with WASM OJ Wonderland through this API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: jacob@csie.cool
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import woj
from woj.models.submit200_response import Submit200Response  # noqa: E501
from woj.rest import ApiException

class TestSubmit200Response(unittest.TestCase):
    """Submit200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Submit200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Submit200Response`
        """
        model = woj.models.submit200_response.Submit200Response()  # noqa: E501
        if include_optional :
            return Submit200Response(
                submission_id = ''
            )
        else :
            return Submit200Response(
                submission_id = '',
        )
        """

    def testSubmit200Response(self):
        """Test Submit200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
