# coding: utf-8

"""
    WASM OJ Wonderland API

    You can interact with WASM OJ Wonderland through this API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: jacob@csie.cool
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import woj
from woj.api.submission_api import SubmissionApi  # noqa: E501
from woj.rest import ApiException


class TestSubmissionApi(unittest.TestCase):
    """SubmissionApi unit test stubs"""

    def setUp(self):
        self.api = woj.api.submission_api.SubmissionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_submission_get(self):
        """Test case for api_submission_get

        """
        pass

    def test_api_submission_id_get(self):
        """Test case for api_submission_id_get

        """
        pass

    def test_submit(self):
        """Test case for submit

        """
        pass


if __name__ == '__main__':
    unittest.main()
