# coding: utf-8

"""
    WASM OJ Wonderland API

    You can interact with WASM OJ Wonderland through this API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: jacob@csie.cool
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from woj.models.api_submission_get200_response_submissions_inner import ApiSubmissionGet200ResponseSubmissionsInner

class ApiSubmissionGet200Response(BaseModel):
    """
    ApiSubmissionGet200Response
    """
    submissions: conlist(ApiSubmissionGet200ResponseSubmissionsInner) = Field(...)
    __properties = ["submissions"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiSubmissionGet200Response:
        """Create an instance of ApiSubmissionGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in submissions (list)
        _items = []
        if self.submissions:
            for _item in self.submissions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['submissions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiSubmissionGet200Response:
        """Create an instance of ApiSubmissionGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiSubmissionGet200Response.parse_obj(obj)

        _obj = ApiSubmissionGet200Response.parse_obj({
            "submissions": [ApiSubmissionGet200ResponseSubmissionsInner.from_dict(_item) for _item in obj.get("submissions")] if obj.get("submissions") is not None else None
        })
        return _obj

