# coding: utf-8

"""
    WASM OJ Wonderland API

    You can interact with WASM OJ Wonderland through this API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: jacob@csie.cool
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class ApiProblemIdGet200ResponseProblemPolicyInner(BaseModel):
    """
    ApiProblemIdGet200ResponseProblemPolicyInner
    """
    budget: Union[StrictFloat, StrictInt] = Field(...)
    memory: Union[StrictFloat, StrictInt] = Field(...)
    score: Union[StrictFloat, StrictInt] = Field(...)
    __properties = ["budget", "memory", "score"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiProblemIdGet200ResponseProblemPolicyInner:
        """Create an instance of ApiProblemIdGet200ResponseProblemPolicyInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiProblemIdGet200ResponseProblemPolicyInner:
        """Create an instance of ApiProblemIdGet200ResponseProblemPolicyInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiProblemIdGet200ResponseProblemPolicyInner.parse_obj(obj)

        _obj = ApiProblemIdGet200ResponseProblemPolicyInner.parse_obj({
            "budget": obj.get("budget"),
            "memory": obj.get("memory"),
            "score": obj.get("score")
        })
        return _obj

